"""minor modification

Revision ID: 0b6bba71c0e1
Revises: d4e7b51a71be
Create Date: 2017-05-30 00:27:24.552684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6bba71c0e1'
down_revision = 'd4e7b51a71be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
